# -*- coding: utf-8 -*-
"""
Cultures Saga — Generate mapdata/ from SAGA_GAME_HACK
=======================================================
Copies essential game resource files (map.dat, map.ini, text/ger/ resources,
sfx) from the game reference directory to mapdata/ for CI-compatible builds.

mapdata/ is committed to the git repo so the GitHub Actions workflow can
build without requiring external game data.

Essential files per map:
  - map.dat            (binary map data, 1-2 MB)
  - map.ini            (map metadata)
  - text/ger/          (German source resources: hlt, fnt, pcx, bmp)
  - sfx/ger/           (voice-over audio: wav)

Excluded (generated by build_text.py):
  - strings.ini, strings.cif, briefings.txt
  - eng/, l10/, pol/ language directories

Usage:
  python generate_mapdata.py           # Full generation
  python generate_mapdata.py --dry-run # Preview only
"""
import argparse
import shutil
import sys
import time
from pathlib import Path

PROJ_ROOT = Path(__file__).resolve().parent
GAME_DIR = Path(r"G:/Projects/Cultures_Saga_CN/SAGA_GAME_HACK")
MAPDATA = PROJ_ROOT / "mapdata"

# Files to exclude from text/ger/ (generated by build)
SKIP_TEXT_FILES = {"strings.ini", "strings.cif", "briefings.txt"}


def is_essential_text_file(path: Path) -> bool:
    """Check if a file under text/ger/ is essential (not generated by build)."""
    return path.name not in SKIP_TEXT_FILES


def generate_mapdata(dry_run: bool = False) -> int:
    """Copy essential map files from GAME_DIR to mapdata/."""
    src_maps = GAME_DIR / "Data" / "maps"
    src_user = GAME_DIR / "DataX" / "UserCampaigns"
    dst_maps = MAPDATA / "Data" / "maps"
    dst_user = MAPDATA / "DataX" / "UserCampaigns"

    copied = 0

    # --- Main campaign maps ---
    if not src_maps.exists():
        print(f"ERROR: {src_maps} not found")
        sys.exit(1)

    print(f"Scanning {src_maps} ...")
    for md in sorted(src_maps.iterdir()):
        if not md.is_dir():
            continue
        dst = dst_maps / md.name
        if not dry_run:
            dst.mkdir(parents=True, exist_ok=True)

        # map.dat
        src_file = md / "map.dat"
        if src_file.exists():
            if not dry_run:
                shutil.copy2(src_file, dst / "map.dat")
            copied += 1

        # map.ini
        src_file = md / "map.ini"
        if src_file.exists():
            if not dry_run:
                shutil.copy2(src_file, dst / "map.ini")
            copied += 1

        # text/ger/ resources (hlt, fnt, pcx, bmp — NOT strings.ini/cif/briefings.txt)
        src_ger = md / "text" / "ger"
        if src_ger.exists():
            dst_ger = dst / "text" / "ger"
            for f in src_ger.rglob("*"):
                if f.is_file() and is_essential_text_file(f):
                    rel = f.relative_to(src_ger)
                    dst_file = dst_ger / rel
                    if not dry_run:
                        dst_file.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(f, dst_file)
                    copied += 1

        # sfx/ger/ (voice wav files)
        src_sfx = md / "sfx" / "ger"
        if src_sfx.exists():
            dst_sfx = dst / "sfx" / "ger"
            for f in src_sfx.rglob("*"):
                if f.is_file():
                    rel = f.relative_to(src_sfx)
                    dst_file = dst_sfx / rel
                    if not dry_run:
                        dst_file.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copy2(f, dst_file)
                    copied += 1

        if not dry_run:
            print(f"  [OK] {md.name}")

    # --- User campaign maps ---
    if src_user.exists():
        print(f"Scanning {src_user} ...")
        for campaign_dir in sorted(src_user.iterdir()):
            if not campaign_dir.is_dir():
                continue
            for md in sorted(campaign_dir.iterdir()):
                if not md.is_dir():
                    continue
                cur = md / "currentusermap"
                if not cur.exists():
                    continue
                dst_cur = dst_user / campaign_dir.name / md.name / "currentusermap"
                if not dry_run:
                    dst_cur.mkdir(parents=True, exist_ok=True)

                # map.dat, map.ini
                for fn in ("map.dat", "map.ini"):
                    src_file = cur / fn
                    if src_file.exists():
                        if not dry_run:
                            shutil.copy2(src_file, dst_cur / fn)
                        copied += 1

                # text/ger/ resources
                src_ger = cur / "text" / "ger"
                if src_ger.exists():
                    dst_ger = dst_cur / "text" / "ger"
                    for f in src_ger.rglob("*"):
                        if f.is_file() and is_essential_text_file(f):
                            rel = f.relative_to(src_ger)
                            dst_file = dst_ger / rel
                            if not dry_run:
                                dst_file.parent.mkdir(parents=True, exist_ok=True)
                                shutil.copy2(f, dst_file)
                            copied += 1

                if not dry_run:
                    print(f"  [OK] {campaign_dir.name}/{md.name}")

    if dry_run:
        print(f"\nWould copy ~{copied} files to {MAPDATA}")
    else:
        size = sum(f.stat().st_size for f in MAPDATA.rglob("*") if f.is_file())
        print(f"\nCopied {copied} files to {MAPDATA}")
        print(f"Total size: {size / 1024 / 1024:.0f} MB")
    return copied


def main():
    ap = argparse.ArgumentParser(
        description="Generate mapdata/ from game reference directory"
    )
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview only, no files copied")
    args = ap.parse_args()

    print(f"{'='*60}")
    print(f"  Cultures Saga — Generate mapdata/")
    print(f"  Source: {GAME_DIR}")
    print(f"  Output: {MAPDATA}")
    if args.dry_run:
        print(f"  Mode:   DRY-RUN")
    print(f"{'='*60}")

    t0 = time.time()
    generate_mapdata(dry_run=args.dry_run)
    print(f"Done in {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()